[toolchain]


[features]
resolution = true
skip-lint = false

[programs.localnet]
market_contract = "2ofxvLdNQMNFmg6WYovFdnfU6GconP7sYhbipYJXUYuw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

